### ISSUE TITLE
React Hydraton Error happened

### ISSUE THREAD

**Issue by rustmaniac** [SoftTalents/NextJS_Wagmi_Template#2]
Hi, Thanks for your great work.
After checking your template, I've found an hydration error.
It happened when I refresh the site after my wallet connection.
Here is my screenshot.
![hydration_error_1](https://user-images.githubusercontent.com/124241654/221695910-9d9d2b25-bd58-4084-a996-b7ddffa5e195.png)
I am stuck how to resolve this issue.
Can you please check your repository and fix it?

**Comment by fantastic900** [comment]
I also got the same issue and trying to fix it.
I will inform you once I complete.

**Comment by cryptohero92** [comment]
Hydration error fixed, please check.

**Comment by rustmaniac** [comment]
Great, it works now!!!
