### ISSUE TITLE
Metamask Seems to have a problem

### ISSUE THREAD

**Issue by JanTektSan** [SoftTalents/NextJS_Wagmi_Template#5]
Hello, 

First of all, thanks for your great work. 
After some checking your template, I noticed Metamask connection has a problem. 
Here is the screenshot.
![Screenshot_1](https://user-images.githubusercontent.com/131263848/233656801-b6e7e4e4-c0c3-4818-96e9-76dc9a0ed0a9.png)
I hope to know if you have a solution about this problem. 
Thanks again for your excellent work.
Regards

**Comment by cryptohero92** [comment]
From my past experience, I guess there might be a problem in your browser setting.

1) The first case is that you didn't install Metamask extension yet.
2) The 2nd case is that you installed both Metamask and Coinbase. 

Coinbase interferes with Metamask, so if you install both extensions in one browser, the phenomenon you mentioned above will appear.
Please check your browser setting again based on my cases.

**Comment by JanTektSan** [comment]
Thank you!
I didn't know it and you are right!!!
After removing coinbase, I noticed metamask unsupported issue removed. :)
